export const CommonConstants = {
  IMAGE_URL_1: $r("app.media.1"),
  IMAGE_URL_2: $r("app.media.2"),
  IMAGE_URL_3: $r("app.media.3"),
  IMAGE_URL_4: $r("app.media.4"),
  HOME_ICON: $r("app.media.home"),
  VIDEO_ICON: $r("app.media.video"),
  STUDY_ICON: $r("app.media.learn"),
  PROFILE_ICON: $r("app.media.user"),
  BANNER_IMAGES: [
    { url: $r("app.media.congbai"), description: '葱白' },
    { url: $r("app.media.1"), description: '葱' },
    { url: $r("app.media.2"), description: '防风' }
  ]
};